language: python
python:
  - 2.7
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  -  python -m SimpleHTTPServer 6543 &
  - sleep 5
script: phantomjs test/run-qunit.js "http://localhost:6543/test/index.html"